import * as ImagePicker from 'expo-image-picker';
import { useLocalSearchParams } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { AdminShell } from '@/src/components/AdminShell';
import { ChoiceRail } from '@/src/components/ChoiceRail';
import { getAdminCarDetail, uploadCarPhoto } from '@/src/lib/api';
import { useApp } from '@/src/state/AppProvider';
import { colors } from '@/src/theme/colors';
type Group='exterior'|'interior'|'detail';
export default function CarMedia(){const p=colors[useColorScheme()==='dark'?'dark':'light'];const {id}=useLocalSearchParams<{id:string}>();const {token}=useApp();const carId=Number(id);const [car,setCar]=useState<any>(null);const [group,setGroup]=useState<Group>('exterior');const [busy,setBusy]=useState(false);const load=useCallback(async()=>{if(!token||!carId)return;try{setCar(await getAdminCarDetail(token,carId))}catch(e){Alert.alert('Ошибка',e instanceof Error?e.message:'Не удалось загрузить')}},[carId,token]);useEffect(()=>{void load()},[load]);const pick=async()=>{if(!token||!car)return;const variant=car.variants?.[0];if(!variant?.id){Alert.alert('Нет цветового варианта','Сначала добавьте цветовой вариант автомобилю.');return}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,quality:1});if(result.canceled)return;setBusy(true);try{for(let i=0;i<result.assets.length;i++){const a=result.assets[i];await uploadCarPhoto(token,{carId,variantId:variant.id,group,isCover:group==='exterior'&&i===0,sortOrder:i,asset:{uri:a.uri,name:a.fileName,mimeType:a.mimeType}})}Alert.alert('Готово',`${result.assets.length} фото загружено.`);await load()}catch(e){Alert.alert('Не удалось загрузить',e instanceof Error?e.message:'Ошибка')}finally{setBusy(false)}};return <AdminShell title="Фотографии" subtitle={car?`${car.brand} ${car.model}`:'Загрузка данных…'}>{!car?<ActivityIndicator color={p.text} style={{marginTop:42}}/>:<><Text style={[s.label,{color:p.secondary}]}>ГРУППА</Text><ChoiceRail value={group} onChange={setGroup} items={[{value:'exterior',label:'Кузов'},{value:'interior',label:'Салон'},{value:'detail',label:'Детали'}]}/><View style={[s.info,{backgroundColor:p.surface,borderColor:p.hairline}]}><SymbolView name={{ios:'photo.stack.fill',android:'photo_library',web:'photo_library'}} size={24} tintColor={p.text}/><Text style={[s.infoTitle,{color:p.text}]}>R2 Media</Text><Text style={[s.infoText,{color:p.secondary}]}>Фото отправляются в тот же `/api/car-media`, который использует веб Control System. Первый кадр кузова становится cover.</Text></View><Pressable disabled={busy} onPress={()=>void pick()} style={[s.button,{backgroundColor:p.text},busy&&{opacity:.6}]}>{busy?<ActivityIndicator color={p.background}/>:<><SymbolView name={{ios:'photo.badge.plus',android:'add_photo_alternate',web:'add_photo_alternate'}} size={18} tintColor={p.background}/><Text style={[s.buttonText,{color:p.background}]}>Выбрать фотографии</Text></>}</Pressable><Text style={[s.count,{color:p.secondary}]}>Вариантов: {car.variants?.length??0}</Text></>}</AdminShell>}
const s=StyleSheet.create({label:{fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:.9,marginTop:26,marginBottom:8},info:{marginTop:22,borderRadius:30,borderWidth:StyleSheet.hairlineWidth,padding:20},infoTitle:{marginTop:18,fontSize:22,lineHeight:26,fontWeight:'700'},infoText:{marginTop:8,fontSize:13,lineHeight:20},button:{height:54,borderRadius:27,marginTop:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},buttonText:{fontSize:13,lineHeight:17,fontWeight:'600'},count:{marginTop:14,textAlign:'center',fontSize:11,lineHeight:15}})
