import * as ImagePicker from 'expo-image-picker';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { AdminShell } from '@/src/components/AdminShell';
import { ChoiceRail } from '@/src/components/ChoiceRail';
import { FormField } from '@/src/components/FormField';
import { getHomeMedia, uploadHomeVideo } from '@/src/lib/api';
import type { HomeMediaItem } from '@/src/lib/types';
import { useApp } from '@/src/state/AppProvider';
import { colors } from '@/src/theme/colors';
export default function HomeMedia(){const p=colors[useColorScheme()==='dark'?'dark':'light'];const {token}=useApp();const [items,setItems]=useState<HomeMediaItem[]>([]);const [brand,setBrand]=useState('');const [model,setModel]=useState('');const [price,setPrice]=useState('');const [status,setStatus]=useState<'in_showroom'|'in_stock'|'in_transit'|'made_to_order'|'reserved'>('in_showroom');const [busy,setBusy]=useState(false);const load=useCallback(async()=>{try{setItems(await getHomeMedia())}catch{setItems([])}},[]);useEffect(()=>{void load()},[load]);const pick=async()=>{if(!token)return;const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('Нужен доступ','Разрешите доступ к медиатеке, чтобы выбрать видео.');return}const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['videos'],quality:1});if(r.canceled)return;setBusy(true);try{const a=r.assets[0];await uploadHomeVideo(token,{asset:{uri:a.uri,name:a.fileName,mimeType:a.mimeType},brand,model,price,status});await load();Alert.alert('Готово','Hero-видео загружено в R2.')}catch(e){Alert.alert('Ошибка',e instanceof Error?e.message:'Не удалось загрузить')}finally{setBusy(false)}};return <AdminShell title="Главная" subtitle="Видео-витрина главного экрана из того же R2."><FormField label="Марка" value={brand} onChangeText={setBrand}/><FormField label="Модель" value={model} onChangeText={setModel}/><FormField label="Цена USD" value={price} onChangeText={setPrice} keyboardType="numeric"/><Text style={[s.label,{color:p.secondary}]}>СТАТУС</Text><ChoiceRail value={status} onChange={setStatus} items={[{value:'in_showroom',label:'В шоуруме'},{value:'in_stock',label:'В наличии'},{value:'in_transit',label:'В пути'},{value:'made_to_order',label:'Под заказ'},{value:'reserved',label:'Резерв'}]}/><Pressable disabled={busy} onPress={()=>void pick()} style={[s.button,{backgroundColor:p.text},busy&&{opacity:.6}]}>{busy?<ActivityIndicator color={p.background}/>:<Text style={[s.buttonText,{color:p.background}]}>Выбрать и загрузить видео</Text>}</Pressable><Text style={[s.current,{color:p.secondary}]}>Сейчас опубликовано: {items.length}</Text><View style={s.list}>{items.map(v=><View key={v.key} style={[s.card,{backgroundColor:p.surface,borderColor:p.hairline}]}><Text style={[s.brand,{color:p.secondary}]}>{v.brand.toUpperCase()}</Text><Text style={[s.model,{color:p.text}]}>{v.model}</Text><Text style={[s.meta,{color:p.secondary}]}>{v.status} · {Math.round(v.size/1024/1024)} MB</Text></View>)}</View></AdminShell>}
const s=StyleSheet.create({label:{fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:.9,marginTop:18,marginBottom:8},button:{height:54,borderRadius:27,marginTop:22,alignItems:'center',justifyContent:'center'},buttonText:{fontSize:13,lineHeight:17,fontWeight:'600'},current:{marginTop:18,fontSize:11,lineHeight:15},list:{marginTop:12,gap:8},card:{borderRadius:24,borderWidth:StyleSheet.hairlineWidth,padding:14},brand:{fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1.1},model:{marginTop:4,fontSize:17,lineHeight:21,fontWeight:'700'},meta:{marginTop:4,fontSize:10,lineHeight:14}})
