import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { AdminShell } from '@/src/components/AdminShell';
import { getVehicleRequests, updateVehicleRequest } from '@/src/lib/api';
import type { VehicleRequest } from '@/src/lib/types';
import { useApp } from '@/src/state/AppProvider';
import { colors } from '@/src/theme/colors';
const labels:Record<VehicleRequest['status'],string>={new:'Новый',contacted:'Связались',sourcing:'Поиск',offered:'Предложено',completed:'Завершён',cancelled:'Отменён'};
export default function Requests(){const p=colors[useColorScheme()==='dark'?'dark':'light'];const {token}=useApp();const [items,setItems]=useState<VehicleRequest[]>([]);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{if(!token)return;try{setItems(await getVehicleRequests(token))}catch(e){Alert.alert('Ошибка',e instanceof Error?e.message:'Не удалось загрузить')}finally{setLoading(false)}},[token]);useEffect(()=>{void load()},[load]);const next=async(item:VehicleRequest,status:VehicleRequest['status'])=>{if(!token)return;try{await updateVehicleRequest(token,item.id,status);void load()}catch(e){Alert.alert('Ошибка',e instanceof Error?e.message:'Не удалось обновить')}};return <AdminShell title="Запросы" subtitle="Персональный подбор из сайта и мобильного приложения.">{loading?<ActivityIndicator color={p.text} style={{marginTop:42}}/>:<View style={s.list}>{items.map(r=><View key={r.id} style={[s.card,{backgroundColor:p.surface,borderColor:p.hairline}]}><View style={s.top}><View style={{flex:1}}><Text style={[s.code,{color:p.secondary}]}>{r.code}</Text><Text style={[s.model,{color:p.text}]}>{r.brand} {r.model}</Text><Text style={[s.client,{color:p.secondary}]}>{r.customerName} · {r.phone}</Text></View><Text style={[s.status,{color:r.status==='cancelled'?'#FF453A':r.status==='completed'?'#34C759':p.text}]}>{labels[r.status]}</Text></View>{r.maxBudget?<Text style={[s.budget,{color:p.text}]}>до {r.maxBudget.toLocaleString()} {r.currency}</Text>:null}{r.importantOptions?<Text style={[s.note,{color:p.secondary}]}>{r.importantOptions}</Text>:null}<View style={s.actions}>{(['contacted','sourcing','offered','completed'] as VehicleRequest['status'][]).map(st=><Pressable key={st} onPress={()=>void next(r,st)} style={[s.chip,{backgroundColor:p.fill}]}><Text style={[s.chipText,{color:p.text}]}>{labels[st]}</Text></Pressable>)}</View></View>)}</View>}</AdminShell>}
const s=StyleSheet.create({list:{marginTop:24,gap:10},card:{borderRadius:28,borderWidth:StyleSheet.hairlineWidth,padding:16},top:{flexDirection:'row',gap:10},code:{fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1.1},model:{marginTop:4,fontSize:19,lineHeight:23,fontWeight:'700'},client:{marginTop:4,fontSize:11,lineHeight:15},status:{fontSize:10,lineHeight:14,fontWeight:'600'},budget:{marginTop:13,fontSize:16,lineHeight:20,fontWeight:'700'},note:{marginTop:7,fontSize:12,lineHeight:18},actions:{marginTop:15,flexDirection:'row',flexWrap:'wrap',gap:7},chip:{height:36,borderRadius:18,paddingHorizontal:12,justifyContent:'center'},chipText:{fontSize:10,lineHeight:13,fontWeight:'600'}})
