import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { AdminShell } from '@/src/components/AdminShell';
import { getVisits, updateVisit } from '@/src/lib/api';
import type { Visit } from '@/src/lib/types';
import { useApp } from '@/src/state/AppProvider';
import { colors } from '@/src/theme/colors';
const labels:Record<Visit['status'],string>={new:'Новый',confirmed:'Подтверждён',completed:'Завершён',cancelled:'Отменён'};
export default function Visits(){const p=colors[useColorScheme()==='dark'?'dark':'light'];const {token}=useApp();const [items,setItems]=useState<Visit[]>([]);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{if(!token)return;try{setItems(await getVisits(token))}catch(e){Alert.alert('Ошибка',e instanceof Error?e.message:'Не удалось загрузить')}finally{setLoading(false)}},[token]);useEffect(()=>{void load()},[load]);const next=async(item:Visit,status:Visit['status'])=>{if(!token)return;try{await updateVisit(token,item.id,status);void load()}catch(e){Alert.alert('Ошибка',e instanceof Error?e.message:'Не удалось обновить')}};return <AdminShell title="Визиты" subtitle="Бронирования, созданные на сайте и в приложении.">{loading?<ActivityIndicator color={p.text} style={{marginTop:42}}/>:<View style={s.list}>{items.map(v=><View key={v.id} style={[s.card,{backgroundColor:p.surface,borderColor:p.hairline}]}><View style={s.top}><View><Text style={[s.code,{color:p.secondary}]}>{v.code}</Text><Text style={[s.name,{color:p.text}]}>{v.customerName}</Text></View><Text style={[s.status,{color:v.status==='cancelled'?'#FF453A':v.status==='completed'?'#34C759':p.text}]}>{labels[v.status]}</Text></View><Text style={[s.meta,{color:p.secondary}]}>{v.visitDate} · {v.timeSlot}</Text><Text style={[s.meta,{color:p.secondary}]}>{v.carLabel||v.brand||'Автомобиль не выбран'} · {v.phone}</Text><View style={s.actions}><Pressable onPress={()=>void next(v,'confirmed')} style={[s.chip,{backgroundColor:p.fill}]}><Text style={[s.chipText,{color:p.text}]}>Подтвердить</Text></Pressable><Pressable onPress={()=>void next(v,'completed')} style={[s.chip,{backgroundColor:p.fill}]}><Text style={[s.chipText,{color:p.text}]}>Завершить</Text></Pressable><Pressable onPress={()=>void next(v,'cancelled')} style={[s.chip,{backgroundColor:'rgba(255,69,58,.10)'}]}><Text style={[s.chipText,{color:'#FF453A'}]}>Отмена</Text></Pressable></View></View>)}</View>}</AdminShell>}
const s=StyleSheet.create({list:{marginTop:24,gap:10},card:{borderRadius:28,borderWidth:StyleSheet.hairlineWidth,padding:16},top:{flexDirection:'row',justifyContent:'space-between',gap:10},code:{fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1.1},name:{marginTop:4,fontSize:18,lineHeight:22,fontWeight:'700'},status:{fontSize:11,lineHeight:15,fontWeight:'600'},meta:{marginTop:6,fontSize:11,lineHeight:16},actions:{marginTop:15,flexDirection:'row',flexWrap:'wrap',gap:7},chip:{height:36,borderRadius:18,paddingHorizontal:12,justifyContent:'center'},chipText:{fontSize:10,lineHeight:13,fontWeight:'600'}})
