import { Image } from 'expo-image';
import { useLocalSearchParams } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View, useColorScheme, useWindowDimensions } from 'react-native';
import { CarCard } from '@/src/components/CarCard';
import { SiteGlass } from '@/src/components/SiteGlass';
import { SiteHeader } from '@/src/components/SiteHeader';
import { getCatalog } from '@/src/lib/api';
import type { CarStatus, CatalogCar } from '@/src/lib/types';
import { useApp } from '@/src/state/AppProvider';
import { brandNames, siteAssets } from '@/src/site/assets';
import { colors } from '@/src/theme/colors';

type Filter='all'|'available'|CarStatus;
const filters: Array<{key:Filter;ru:string;uz:string}>=[
 {key:'all',ru:'Все',uz:'Barchasi'},{key:'available',ru:'Доступные',uz:'Mavjud'},{key:'in_showroom',ru:'В шоуруме',uz:'Shourumda'},{key:'in_stock',ru:'В наличии',uz:'Omborda'},{key:'in_transit',ru:'В пути',uz:'Yo‘lda'},{key:'made_to_order',ru:'Под заказ',uz:'Buyurtma'},{key:'reserved',ru:'Резерв',uz:'Rezerv'},{key:'sold',ru:'Проданы',uz:'Sotilgan'}
];
function match(car:CatalogCar,f:Filter){if(f==='all')return car.status!=='hidden';if(f==='available')return car.status==='in_showroom'||car.status==='in_stock';return car.status===f}

export default function CatalogScreen(){
 const p=colors[useColorScheme()==='dark'?'dark':'light']; const {width}=useWindowDimensions(); const {language}=useApp(); const params=useLocalSearchParams<{brand?:string;status?:string}>();
 const [cars,setCars]=useState<CatalogCar[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [query,setQuery]=useState('');const [brand,setBrand]=useState<string>('all');const [status,setStatus]=useState<Filter>('all');const [twoColumns,setTwoColumns]=useState(false);
 useEffect(()=>{if(typeof params.brand==='string'&&params.brand)setBrand(params.brand);if(typeof params.status==='string'&&filters.some(f=>f.key===params.status))setStatus(params.status as Filter)},[params.brand,params.status]);
 const load=useCallback(async()=>{try{setCars(await getCatalog(100))}finally{setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{void load()},[load]);
 const result=useMemo(()=>cars.filter(car=>{const q=query.trim().toLowerCase();const text=`${car.brand} ${car.model} ${car.trim??''}`.toLowerCase();return (brand==='all'||car.brand===brand)&&match(car,status)&&(!q||text.includes(q))}),[brand,cars,query,status]);
 const grid=twoColumns&&width>=390;
 return <View style={[s.page,{backgroundColor:p.background}]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.shell}><SiteHeader/>
 <View style={s.intro}><Text style={[s.kicker,{color:p.secondary}]}>AUTO SALE UMAR · CATALOG</Text><Text style={[s.title,{color:p.text}]}>{language==='ru'?'Автомобили':'Avtomobillar'}</Text><Text style={[s.subtitle,{color:p.secondary}]}>{language==='ru'?'Единый каталог Auto Sale Umar — реальные автомобили и актуальные статусы.':'Auto Sale Umar yagona katalogi — real avtomobillar va dolzarb statuslar.'}</Text></View>
 <SiteGlass style={s.search}><SymbolView name={{ios:'magnifyingglass',android:'search',web:'search'}} size={18} tintColor={p.secondary}/><TextInput value={query} onChangeText={setQuery} placeholder={language==='ru'?'Марка, модель, комплектация':'Marka, model, komplektatsiya'} placeholderTextColor={p.secondary} style={[s.input,{color:p.text}]}/>{query?<Pressable onPress={()=>setQuery('')}><SymbolView name={{ios:'xmark.circle.fill',android:'cancel',web:'cancel'}} size={18} tintColor={p.tertiary}/></Pressable>:null}</SiteGlass>
 </View>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.brandRail}><Pressable onPress={()=>setBrand('all')} style={[s.brandChip,brand==='all'&&{borderColor:p.text}]}><View style={[s.brandLogo,{backgroundColor:p.surface,borderColor:p.hairline}]}><SymbolView name={{ios:'sparkles',android:'auto_awesome',web:'auto_awesome'}} size={20} tintColor={p.text}/></View><Text style={[s.brandText,{color:brand==='all'?p.text:p.secondary}]}>Все</Text></Pressable>{brandNames.map(name=><Pressable key={name} onPress={()=>setBrand(name)} style={[s.brandChip,brand===name&&{borderColor:p.text}]}><View style={[s.brandLogo,{backgroundColor:p.surface,borderColor:p.hairline}]}><Image source={siteAssets.brands[name]} style={s.brandImg} contentFit="contain"/></View><Text numberOfLines={1} style={[s.brandText,{color:brand===name?p.text:p.secondary}]}>{name}</Text></Pressable>)}</ScrollView>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.statusRail}>{filters.map(f=><Pressable key={f.key} onPress={()=>setStatus(f.key)}><SiteGlass interactive={status===f.key} style={[s.statusChip,status===f.key&&{borderColor:p.text}]}><Text style={[s.statusText,{color:status===f.key?p.text:p.secondary}]}>{language==='ru'?f.ru:f.uz}</Text></SiteGlass></Pressable>)}</ScrollView>
 <View style={s.meta}><Text style={[s.count,{color:p.secondary}]}>{loading?'…':language==='ru'?`${result.length} автомобилей`:`${result.length} avtomobil`}</Text><View style={s.layoutToggle}><Pressable onPress={()=>setTwoColumns(false)} style={[s.layoutBtn,{backgroundColor:!twoColumns?p.fill:'transparent'}]}><SymbolView name={{ios:'rectangle.grid.1x2',android:'view_agenda',web:'view_agenda'}} size={17} tintColor={!twoColumns?p.text:p.secondary}/></Pressable><Pressable onPress={()=>setTwoColumns(true)} style={[s.layoutBtn,{backgroundColor:twoColumns?p.fill:'transparent'}]}><SymbolView name={{ios:'square.grid.2x2',android:'grid_view',web:'grid_view'}} size={17} tintColor={twoColumns?p.text:p.secondary}/></Pressable></View></View>
 {loading?<ActivityIndicator style={{marginTop:50}} color={p.text}/>:result.length?<View style={[s.grid,grid&&s.gridTwo]}>{result.map(car=><CarCard key={car.id} car={car} language={language} style={grid?s.twoCard:undefined}/>)}</View>:<View style={s.empty}><SymbolView name={{ios:'car',android:'directions_car',web:'directions_car'}} size={42} tintColor={p.tertiary}/><Text style={[s.emptyTitle,{color:p.text}]}>{language==='ru'?'Ничего не найдено':'Hech narsa topilmadi'}</Text><Text style={[s.emptyText,{color:p.secondary}]}>{language==='ru'?'Измените фильтры или запрос.':'Filtr yoki so‘rovni o‘zgartiring.'}</Text></View>}
 </ScrollView></View>
}
const s=StyleSheet.create({page:{flex:1},content:{paddingBottom:130},shell:{width:'100%',maxWidth:760,alignSelf:'center',paddingHorizontal:16},intro:{paddingHorizontal:4,paddingTop:18,paddingBottom:20},kicker:{fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:1.7},title:{marginTop:7,fontSize:42,lineHeight:45,fontWeight:'700',letterSpacing:-1.7},subtitle:{marginTop:10,fontSize:15,lineHeight:22,maxWidth:600},search:{height:54,borderRadius:27,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:10},input:{flex:1,fontSize:16,lineHeight:20},brandRail:{paddingHorizontal:16,paddingTop:24,paddingRight:28,gap:12},brandChip:{width:74,borderRadius:26,borderWidth:1,borderColor:'transparent',alignItems:'center',paddingVertical:7},brandLogo:{width:54,height:54,borderRadius:27,borderWidth:StyleSheet.hairlineWidth,alignItems:'center',justifyContent:'center'},brandImg:{width:37,height:37},brandText:{marginTop:6,fontSize:9,lineHeight:12,textAlign:'center',maxWidth:72},statusRail:{paddingHorizontal:16,paddingTop:18,paddingRight:28,gap:8},statusChip:{height:40,borderRadius:20,paddingHorizontal:14,justifyContent:'center',borderWidth:StyleSheet.hairlineWidth,borderColor:'transparent'},statusText:{fontSize:12,lineHeight:15,fontWeight:'600'},meta:{maxWidth:760,width:'100%',alignSelf:'center',paddingHorizontal:20,paddingTop:26,paddingBottom:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},count:{fontSize:12,lineHeight:16,fontWeight:'500'},layoutToggle:{flexDirection:'row',gap:5},layoutBtn:{width:36,height:36,borderRadius:18,alignItems:'center',justifyContent:'center'},grid:{maxWidth:760,width:'100%',alignSelf:'center',paddingHorizontal:16,gap:14},gridTwo:{flexDirection:'row',flexWrap:'wrap'},twoCard:{width:'48.2%'},empty:{paddingTop:80,alignItems:'center',paddingHorizontal:30},emptyTitle:{marginTop:18,fontSize:21,lineHeight:25,fontWeight:'700'},emptyText:{marginTop:6,fontSize:14,lineHeight:20,textAlign:'center'}})
