import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { SymbolView } from 'expo-symbols';
import { CarCard } from '@/src/components/CarCard';
import { SiteHeader } from '@/src/components/SiteHeader';
import { getCatalog } from '@/src/lib/api';
import type { CatalogCar } from '@/src/lib/types';
import { useApp } from '@/src/state/AppProvider';
import { colors } from '@/src/theme/colors';
export default function FavoritesScreen(){const p=colors[useColorScheme()==='dark'?'dark':'light'];const {favorites,language}=useApp();const [cars,setCars]=useState<CatalogCar[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{try{setCars(await getCatalog())}finally{setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{void load()},[load]);const result=useMemo(()=>cars.filter(c=>favorites.includes(c.slug)),[cars,favorites]);return <View style={[s.page,{backgroundColor:p.background}]}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);void load()}}/>} contentContainerStyle={s.content}><View style={s.shell}><SiteHeader/><View style={s.intro}><Text style={[s.kicker,{color:p.secondary}]}>AUTO SALE UMAR</Text><Text style={[s.title,{color:p.text}]}>{language==='ru'?'Избранное':'Tanlanganlar'}</Text><Text style={[s.text,{color:p.secondary}]}>{language==='ru'?'Сохранённые автомобили остаются здесь, пока вы сравниваете варианты.':'Saqlangan avtomobillar tanlov davomida shu yerda qoladi.'}</Text></View>{loading?<ActivityIndicator color={p.text}/>:result.length?<View style={s.grid}>{result.map(c=><CarCard key={c.id} car={c} language={language}/>)}</View>:<View style={s.empty}><View style={[s.emptyIcon,{backgroundColor:p.fill}]}><SymbolView name={{ios:'heart',android:'favorite_border',web:'favorite_border'}} size={31} tintColor={p.secondary}/></View><Text style={[s.emptyTitle,{color:p.text}]}>{language==='ru'?'Пока пусто':'Hozircha bo‘sh'}</Text><Text style={[s.emptyText,{color:p.secondary}]}>{language==='ru'?'Добавляйте автомобили сердцем на странице автомобиля.':'Avtomobil sahifasida yurak orqali saqlang.'}</Text></View>}</View></ScrollView></View>}
const s=StyleSheet.create({page:{flex:1},content:{paddingBottom:130},shell:{width:'100%',maxWidth:760,alignSelf:'center',paddingHorizontal:16},intro:{paddingHorizontal:4,paddingTop:20,paddingBottom:28},kicker:{fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:1.7},title:{marginTop:7,fontSize:42,lineHeight:45,fontWeight:'700',letterSpacing:-1.7},text:{marginTop:10,fontSize:15,lineHeight:22,maxWidth:560},grid:{gap:14},empty:{alignItems:'center',paddingTop:90,paddingHorizontal:30},emptyIcon:{width:68,height:68,borderRadius:34,alignItems:'center',justifyContent:'center'},emptyTitle:{marginTop:18,fontSize:22,lineHeight:26,fontWeight:'700'},emptyText:{marginTop:7,fontSize:14,lineHeight:20,textAlign:'center'}})
