import { router } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { useState } from 'react';
import { ActivityIndicator, Alert, Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View, useColorScheme } from 'react-native';
import { SiteGlass } from '@/src/components/SiteGlass';
import { SiteHeader } from '@/src/components/SiteHeader';
import { useApp } from '@/src/state/AppProvider';
import { colors } from '@/src/theme/colors';

type TileProps={title:string;subtitle:string;icon:string;onPress:()=>void};
function ControlTile({title,subtitle,icon,onPress}:TileProps){const p=colors[useColorScheme()==='dark'?'dark':'light'];return <Pressable onPress={onPress} style={({pressed})=>[s.controlTile,{backgroundColor:p.surface,borderColor:p.hairline},pressed&&s.pressed]}><View style={[s.controlIcon,{backgroundColor:p.fill}]}><SymbolView name={{ios:icon as any,android:'settings',web:'settings'} as any} size={20} tintColor={p.text}/></View><View style={s.controlCopy}><Text style={[s.controlTitle,{color:p.text}]}>{title}</Text><Text style={[s.controlSubtitle,{color:p.secondary}]}>{subtitle}</Text></View><SymbolView name={{ios:'chevron.right',android:'chevron_right',web:'chevron_right'}} size={14} tintColor={p.secondary}/></Pressable>}

export default function ProfileScreen(){
 const p=colors[useColorScheme()==='dark'?'dark':'light'];const {language,setLanguage,themeMode,setThemeMode,user,token,controlMode,setControlMode,login,logout}=useApp();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);
 const doLogin=async()=>{setBusy(true);try{await login(email,password)}catch(e){Alert.alert('Не удалось войти',e instanceof Error?e.message:'Проверьте данные')}finally{setBusy(false)}};
 const isAdmin=user?.role==='admin'||user?.role==='super_admin';
 return <View style={[s.page,{backgroundColor:p.background}]}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.shell}><SiteHeader profile={false}/><View style={s.intro}><Text style={[s.kicker,{color:p.secondary}]}>AUTO SALE UMAR</Text><Text style={[s.title,{color:p.text}]}>{language==='ru'?'Профиль':'Profil'}</Text><Text style={[s.text,{color:p.secondary}]}>{user?`${user.fullName} · ${user.role}`:(language==='ru'?'Настройки клиента и защищённый вход для команды Auto Sale Umar.':'Mijoz sozlamalari va Auto Sale Umar jamoasi uchun himoyalangan kirish.')}</Text></View>
 {user?<View style={s.modeWrap}><SiteGlass style={s.segment}><Pressable onPress={()=>setControlMode('client')} style={[s.segmentItem,controlMode==='client'&&{backgroundColor:p.surface}]}><Text style={[s.segmentText,{color:controlMode==='client'?p.text:p.secondary}]}>Клиент</Text></Pressable><Pressable onPress={()=>setControlMode('control')} style={[s.segmentItem,controlMode==='control'&&{backgroundColor:p.surface}]}><Text style={[s.segmentText,{color:controlMode==='control'?p.text:p.secondary}]}>Control System</Text></Pressable></SiteGlass></View>:null}
 {controlMode==='control'&&user&&token?<View><View style={[s.userCard,{backgroundColor:'#111214'}]}><Text style={s.userKicker}>AUTO SALE UMAR · CONTROL SYSTEM</Text><Text style={s.userName}>{user.fullName}</Text><Text style={s.userEmail}>{user.email}</Text><View style={s.rolePill}><Text style={s.roleText}>{user.role.replace('_',' ').toUpperCase()}</Text></View></View><View style={s.controlGrid}><ControlTile title="Автомобили" subtitle="Статусы, цены и новые автомобили" icon="car.2.fill" onPress={()=>router.push('/admin/cars')}/>{isAdmin?<ControlTile title="Команда" subtitle="Администраторы и менеджеры" icon="person.2.fill" onPress={()=>router.push('/admin/staff')}/>:null}<ControlTile title="Визиты" subtitle="Бронирования шоурума" icon="calendar" onPress={()=>router.push('/admin/visits')}/><ControlTile title="Запросы" subtitle="Персональный подбор" icon="tray.full.fill" onPress={()=>router.push('/admin/requests')}/>{isAdmin?<ControlTile title="Бренды" subtitle="Обложки марок из R2" icon="photo.on.rectangle.angled" onPress={()=>router.push('/admin/brands')}/>:null}{isAdmin?<ControlTile title="Главная" subtitle="Hero-видео и карточки" icon="play.rectangle.fill" onPress={()=>router.push('/admin/home-media')}/>:null}{isAdmin?<ControlTile title="TV Mode" subtitle="Открыть showroom display" icon="tv.fill" onPress={()=>void Linking.openURL('https://display.autosaleumar.com')}/>:null}</View><Pressable onPress={()=>void logout()} style={[s.logout,{borderColor:p.hairline}]}><Text style={s.logoutText}>Выйти из Control System</Text></Pressable></View>:<View>
 <View style={[s.settingGroup,{backgroundColor:p.surface,borderColor:p.hairline}]}><Text style={[s.groupTitle,{color:p.secondary}]}>ЯЗЫК</Text><View style={s.optionRow}><Pressable onPress={()=>setLanguage('ru')} style={[s.option,language==='ru'&&{backgroundColor:p.fill}]}><Text style={[s.optionText,{color:p.text}]}>Русский</Text></Pressable><Pressable onPress={()=>setLanguage('uz')} style={[s.option,language==='uz'&&{backgroundColor:p.fill}]}><Text style={[s.optionText,{color:p.text}]}>O‘zbek</Text></Pressable></View></View>
 <View style={[s.settingGroup,{backgroundColor:p.surface,borderColor:p.hairline}]}><Text style={[s.groupTitle,{color:p.secondary}]}>ИНТЕРФЕЙС</Text><View style={s.optionRow}>{(['system','light','dark'] as const).map(mode=><Pressable key={mode} onPress={()=>setThemeMode(mode)} style={[s.option,themeMode===mode&&{backgroundColor:p.fill}]}><Text style={[s.optionText,{color:p.text}]}>{mode==='system'?'Система':mode==='light'?'Светлая':'Тёмная'}</Text></Pressable>)}</View></View>
 {!user?<View style={[s.loginCard,{backgroundColor:p.surface,borderColor:p.hairline}]}><View style={[s.loginIcon,{backgroundColor:p.fill}]}><SymbolView name={{ios:'lock.shield.fill',android:'admin_panel_settings',web:'admin_panel_settings'}} size={24} tintColor={p.text}/></View><Text style={[s.loginTitle,{color:p.text}]}>Вход для сотрудников</Text><Text style={[s.loginText,{color:p.secondary}]}>Используется тот же защищённый аккаунт и та же база, что и в веб Control System.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Электронная почта" placeholderTextColor={p.secondary} style={[s.field,{backgroundColor:p.fill,color:p.text}]}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Пароль" placeholderTextColor={p.secondary} style={[s.field,{backgroundColor:p.fill,color:p.text}]}/><Pressable disabled={busy} onPress={()=>void doLogin()} style={[s.loginButton,{backgroundColor:p.text},busy&&{opacity:.6}]}>{busy?<ActivityIndicator color={p.background}/>:<Text style={[s.loginButtonText,{color:p.background}]}>Войти</Text>}</Pressable></View>:null}
 </View>}
 </View></ScrollView></View>
}
const s=StyleSheet.create({page:{flex:1},content:{paddingBottom:130},shell:{width:'100%',maxWidth:760,alignSelf:'center',paddingHorizontal:16},pressed:{opacity:.86},intro:{paddingHorizontal:4,paddingTop:18,paddingBottom:24},kicker:{fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:1.7},title:{marginTop:7,fontSize:42,lineHeight:45,fontWeight:'700',letterSpacing:-1.7},text:{marginTop:10,fontSize:15,lineHeight:22,maxWidth:600},modeWrap:{marginBottom:18},segment:{height:52,borderRadius:26,padding:4,flexDirection:'row'},segmentItem:{flex:1,borderRadius:22,alignItems:'center',justifyContent:'center'},segmentText:{fontSize:13,lineHeight:17,fontWeight:'600'},userCard:{borderRadius:34,padding:22,minHeight:190,justifyContent:'flex-end'},userKicker:{color:'rgba(255,255,255,.50)',fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1.6},userName:{marginTop:8,color:'#fff',fontSize:27,lineHeight:31,fontWeight:'700',letterSpacing:-.7},userEmail:{marginTop:5,color:'rgba(255,255,255,.64)',fontSize:13,lineHeight:17},rolePill:{marginTop:17,alignSelf:'flex-start',borderRadius:15,backgroundColor:'rgba(255,255,255,.12)',paddingHorizontal:10,paddingVertical:7},roleText:{color:'#fff',fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1},controlGrid:{marginTop:16,gap:10},controlTile:{minHeight:78,borderRadius:26,borderWidth:StyleSheet.hairlineWidth,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:12},controlIcon:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center'},controlCopy:{flex:1},controlTitle:{fontSize:15,lineHeight:19,fontWeight:'600'},controlSubtitle:{marginTop:2,fontSize:11,lineHeight:15},logout:{marginTop:18,minHeight:50,borderRadius:25,borderWidth:StyleSheet.hairlineWidth,alignItems:'center',justifyContent:'center'},logoutText:{color:'#FF453A',fontSize:13,lineHeight:17,fontWeight:'600'},settingGroup:{borderRadius:28,borderWidth:StyleSheet.hairlineWidth,padding:16,marginBottom:12},groupTitle:{fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1.5,marginBottom:12},optionRow:{flexDirection:'row',gap:8},option:{flex:1,minHeight:42,borderRadius:21,alignItems:'center',justifyContent:'center'},optionText:{fontSize:12,lineHeight:15,fontWeight:'600'},loginCard:{marginTop:18,borderRadius:32,borderWidth:StyleSheet.hairlineWidth,padding:20},loginIcon:{width:50,height:50,borderRadius:25,alignItems:'center',justifyContent:'center'},loginTitle:{marginTop:18,fontSize:25,lineHeight:29,fontWeight:'700',letterSpacing:-.65},loginText:{marginTop:8,fontSize:13,lineHeight:19},field:{height:52,borderRadius:20,paddingHorizontal:15,fontSize:15,lineHeight:19,marginTop:12},loginButton:{height:52,borderRadius:26,alignItems:'center',justifyContent:'center',marginTop:14},loginButtonText:{fontSize:14,lineHeight:18,fontWeight:'600'}})
