import { router, useLocalSearchParams } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { ChoiceRail } from '@/src/components/ChoiceRail';
import { FormField } from '@/src/components/FormField';
import { SiteHeader } from '@/src/components/SiteHeader';
import { submitVisit } from '@/src/lib/api';
import { colors } from '@/src/theme/colors';
const SLOTS=['09:00–11:00','11:00–13:00','14:00–16:00','16:00–18:00','18:00–20:00'] as const;
function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)}
export default function Booking(){const p=colors[useColorScheme()==='dark'?'dark':'light'];const params=useLocalSearchParams<{carId?:string;brand?:string;carLabel?:string}>();const [name,setName]=useState('');const [phone,setPhone]=useState('');const [date,setDate]=useState(tomorrow());const [slot,setSlot]=useState<(typeof SLOTS)[number]>('11:00–13:00');const [brand,setBrand]=useState(params.brand||'');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{const visit=await submitVisit({customerName:name,phone,visitDate:date,timeSlot:slot,brand,carId:params.carId?Number(params.carId):null,carLabel:params.carLabel||undefined,note});Alert.alert('Визит забронирован',`Код ${visit.code} · ${visit.visitDate} · ${visit.timeSlot}`,[{text:'Готово',onPress:()=>router.back()}])}catch(e){Alert.alert('Не удалось забронировать',e instanceof Error?e.message:'Попробуйте ещё раз')}finally{setBusy(false)}};return <View style={[s.page,{backgroundColor:p.background}]}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.shell}><SiteHeader back profile={false}/><Text style={[s.kicker,{color:p.secondary}]}>SHOWROOM · TASHKENT</Text><Text style={[s.title,{color:p.text}]}>Забронировать визит.</Text><Text style={[s.text,{color:p.secondary}]}>Команда увидит бронирование в том же Control System и подготовит автомобиль к вашему приезду.</Text>{params.carLabel?<View style={[s.carHint,{backgroundColor:p.surface,borderColor:p.hairline}]}><SymbolView name={{ios:'car.fill',android:'directions_car',web:'directions_car'}} size={20} tintColor={p.text}/><Text style={[s.carHintText,{color:p.text}]}>{params.carLabel}</Text></View>:null}<FormField label="Имя" value={name} onChangeText={setName}/><FormField label="Телефон" value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><FormField label="Дата YYYY-MM-DD" value={date} onChangeText={setDate}/><Text style={[s.label,{color:p.secondary}]}>ВРЕМЯ</Text><ChoiceRail value={slot} onChange={setSlot} items={SLOTS.map(x=>({value:x,label:x}))}/><FormField label="Марка" value={brand} onChangeText={setBrand}/><FormField label="Комментарий" value={note} onChangeText={setNote} multiline/><Pressable disabled={busy} onPress={()=>void submit()} style={[s.button,{backgroundColor:p.text},busy&&{opacity:.6}]}><Text style={[s.buttonText,{color:p.background}]}>{busy?'Бронируем…':'Подтвердить визит'}</Text></Pressable></View></ScrollView></View>}
const s=StyleSheet.create({page:{flex:1},content:{paddingBottom:80},shell:{width:'100%',maxWidth:720,alignSelf:'center',paddingHorizontal:16},kicker:{marginTop:24,fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:1.7},title:{marginTop:8,fontSize:38,lineHeight:41,fontWeight:'700',letterSpacing:-1.4},text:{marginTop:10,fontSize:15,lineHeight:22},carHint:{marginTop:22,minHeight:62,borderRadius:24,borderWidth:StyleSheet.hairlineWidth,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:11},carHintText:{fontSize:14,lineHeight:18,fontWeight:'600'},label:{fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:.9,marginTop:18,marginBottom:8},button:{height:56,borderRadius:28,marginTop:28,alignItems:'center',justifyContent:'center'},buttonText:{fontSize:14,lineHeight:18,fontWeight:'600'}})
