import { Image } from 'expo-image';
import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View, useColorScheme } from 'react-native';
import { SiteHeader } from '@/src/components/SiteHeader';
import { absoluteMediaUrl, getCatalog } from '@/src/lib/api';
import { firstPhoto, formatPrice } from '@/src/lib/format';
import type { CatalogCar } from '@/src/lib/types';
import { useApp } from '@/src/state/AppProvider';
import { colors } from '@/src/theme/colors';
function PickCard({car,selected,onPress}:{car:CatalogCar;selected:boolean;onPress:()=>void}){const p=colors[useColorScheme()==='dark'?'dark':'light'];const photo=absoluteMediaUrl(firstPhoto(car));return <Pressable onPress={onPress} style={[s.pick,{backgroundColor:p.surface,borderColor:selected?p.text:p.hairline}]}>{photo?<Image source={{uri:photo}} style={s.pickImg} contentFit="cover"/>:null}<Text numberOfLines={1} style={[s.pickBrand,{color:p.secondary}]}>{car.brand.toUpperCase()}</Text><Text numberOfLines={1} style={[s.pickModel,{color:p.text}]}>{car.model}</Text></Pressable>}
export default function Compare(){const p=colors[useColorScheme()==='dark'?'dark':'light'];const {language}=useApp();const [cars,setCars]=useState<CatalogCar[]>([]);const [a,setA]=useState<CatalogCar|null>(null);const [b,setB]=useState<CatalogCar|null>(null);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{try{setCars((await getCatalog()).slice(0,20))}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const select=(car:CatalogCar)=>{if(a?.id===car.id){setA(null);return}if(b?.id===car.id){setB(null);return}if(!a)setA(car);else if(!b)setB(car);else{setA(b);setB(car)}};const rows:[string,(c:CatalogCar)=>string][]=[['Цена',c=>formatPrice(c,language)],['Год',c=>String(c.year??'—')],['Двигатель',c=>c.engineText||'—'],['Мощность',c=>c.horsepowerHp?`${c.horsepowerHp} л.с.`:'—'],['Привод',c=>c.driveType||'—'],['Коробка',c=>c.transmission||'—'],['Пробег',c=>c.mileageKm!=null?`${c.mileageKm.toLocaleString()} км`:'—'],['0–100',c=>c.acceleration0100?`${c.acceleration0100} сек`:'—']];return <View style={[s.page,{backgroundColor:p.background}]}><ScrollView contentContainerStyle={s.content}><View style={s.shell}><SiteHeader back profile={false}/><Text style={[s.kicker,{color:p.secondary}]}>СРАВНИТЕ ПЕРЕД ВЫБОРОМ</Text><Text style={[s.title,{color:p.text}]}>Два автомобиля. Один понятный выбор.</Text><Text style={[s.text,{color:p.secondary}]}>Выберите два реальных автомобиля из каталога Auto Sale Umar.</Text></View>{loading?<ActivityIndicator color={p.text} style={{marginTop:40}}/>:<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rail}>{cars.map(car=><PickCard key={car.id} car={car} selected={a?.id===car.id||b?.id===car.id} onPress={()=>select(car)}/>)}</ScrollView>}{a&&b?<View style={[s.table,{backgroundColor:p.surface,borderColor:p.hairline}]}><View style={s.tableHead}><Text style={[s.headCar,{color:p.text}]}>{a.brand} {a.model}</Text><Text style={[s.headCar,{color:p.text}]}>{b.brand} {b.model}</Text></View>{rows.map(([label,fn])=><View key={label} style={[s.row,{borderTopColor:p.hairline}]}><Text style={[s.rowLabel,{color:p.secondary}]}>{label}</Text><View style={s.values}><Text style={[s.value,{color:p.text}]}>{fn(a)}</Text><Text style={[s.value,{color:p.text}]}>{fn(b)}</Text></View></View>)}</View>:<Text style={[s.hint,{color:p.secondary}]}>Выберите два автомобиля для сравнения.</Text>}</ScrollView></View>}
const s=StyleSheet.create({page:{flex:1},content:{paddingBottom:80},shell:{width:'100%',maxWidth:760,alignSelf:'center',paddingHorizontal:16},kicker:{marginTop:24,fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:1.6},title:{marginTop:8,fontSize:37,lineHeight:41,fontWeight:'700',letterSpacing:-1.35},text:{marginTop:10,fontSize:15,lineHeight:22},rail:{paddingHorizontal:16,paddingTop:24,paddingRight:28,gap:10},pick:{width:190,borderRadius:26,borderWidth:1,padding:10},pickImg:{height:130,borderRadius:19},pickBrand:{marginTop:11,fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1.1},pickModel:{marginTop:3,fontSize:17,lineHeight:21,fontWeight:'700'},table:{marginHorizontal:16,marginTop:34,borderRadius:30,borderWidth:StyleSheet.hairlineWidth,overflow:'hidden'},tableHead:{padding:18,flexDirection:'row',gap:12},headCar:{flex:1,fontSize:15,lineHeight:20,fontWeight:'700'},row:{borderTopWidth:StyleSheet.hairlineWidth,padding:16},rowLabel:{fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1,textTransform:'uppercase'},values:{marginTop:9,flexDirection:'row',gap:12},value:{flex:1,fontSize:13,lineHeight:18,fontWeight:'600'},hint:{textAlign:'center',paddingTop:46,fontSize:14,lineHeight:20}})
