import { Image } from 'expo-image';
import { router } from 'expo-router';
import { SymbolView } from 'expo-symbols';
import { Linking, Pressable, ScrollView, StyleSheet, Text, View, useColorScheme, useWindowDimensions } from 'react-native';
import { SiteHeader } from '@/src/components/SiteHeader';
import { siteAssets } from '@/src/site/assets';
import { colors } from '@/src/theme/colors';

const MAP='https://yandex.ru/maps/org/auto_sale_umar/98317002086?si=y1pjpr56py0hyc8ar2j2cw1t40';
export default function Location(){const p=colors[useColorScheme()==='dark'?'dark':'light'];const {width}=useWindowDimensions();const cardWidth=Math.min(width*.78,360);return <View style={[s.page,{backgroundColor:p.background}]}><ScrollView contentContainerStyle={s.content}><View style={s.shell}><SiteHeader back/><Text style={[s.kicker,{color:p.secondary}]}>AUTO SALE UMAR · TASHKENT</Text><Text style={[s.title,{color:p.text}]}>Локация{`\n`}шоурума.</Text><Text style={[s.lead,{color:p.secondary}]}>Приезжайте посмотреть автомобиль в спокойной обстановке. Маршрут до Auto Sale Umar открывается одним нажатием.</Text><View style={s.actions}><Pressable onPress={()=>void Linking.openURL(MAP)} style={[s.primary,{backgroundColor:p.text}]}><Text style={[s.primaryText,{color:p.background}]}>Открыть Яндекс Карты</Text><SymbolView name={{ios:'arrow.up.right',android:'north_east',web:'north_east'}} size={15} tintColor={p.background}/></Pressable><Pressable onPress={()=>router.push('/booking')} style={[s.secondary,{backgroundColor:p.surface,borderColor:p.hairline}]}><Text style={[s.secondaryText,{color:p.text}]}>Забронировать визит</Text></Pressable></View><View style={s.hero}><Image source={siteAssets.showroom[0]} style={StyleSheet.absoluteFill} contentFit="cover"/><View style={s.heroShade}/><View style={s.badge}><Text style={s.badgeKicker}>ЛОКАЦИЯ</Text><Text style={s.badgeTitle}>Ташкент · Auto Sale Umar</Text></View></View></View><View style={s.section}><Text style={[s.sectionKicker,{color:p.secondary}]}>ШОУРУМ</Text><Text style={[s.sectionTitle,{color:p.text}]}>Сначала почувствуйте автомобиль.</Text><Text style={[s.sectionText,{color:p.secondary}]}>Посмотрите детали, салон и комплектацию вживую, а команда шоурума подготовит автомобиль к вашему визиту.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rail}>{siteAssets.showroom.slice(1,4).map((x,i)=><Image key={i} source={x} style={[s.image,{width:cardWidth}]} contentFit="cover"/>)}</ScrollView></View><View style={[s.visit,{backgroundColor:'#111214'}]}><Text style={s.visitKicker}>ПЕРЕД ВИЗИТОМ</Text><Text style={s.visitTitle}>Мы подготовим автомобиль заранее.</Text><Text style={s.visitText}>Выберите удобное время или свяжитесь с командой Auto Sale Umar напрямую.</Text><View style={s.visitActions}><Pressable onPress={()=>router.push('/booking')} style={s.white}><Text style={s.whiteText}>Забронировать</Text></Pressable><Pressable onPress={()=>void Linking.openURL('tel:+998771155553')} style={s.dark}><Text style={s.darkText}>+998 77 115 55 53</Text></Pressable></View></View></ScrollView></View>}
const s=StyleSheet.create({page:{flex:1},content:{paddingBottom:120},shell:{width:'100%',maxWidth:760,alignSelf:'center',paddingHorizontal:16},kicker:{marginTop:20,fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:1.7},title:{marginTop:9,fontSize:46,lineHeight:48,fontWeight:'700',letterSpacing:-2},lead:{marginTop:15,maxWidth:620,fontSize:16,lineHeight:24},actions:{marginTop:24,gap:9},primary:{height:54,borderRadius:27,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},primaryText:{fontSize:14,lineHeight:18,fontWeight:'600'},secondary:{height:52,borderRadius:26,borderWidth:StyleSheet.hairlineWidth,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:14,lineHeight:18,fontWeight:'600'},hero:{height:430,borderRadius:36,overflow:'hidden',marginTop:26,backgroundColor:'#111'},heroShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.18)'},badge:{position:'absolute',left:20,right:20,bottom:20},badgeKicker:{color:'rgba(255,255,255,.65)',fontSize:9,lineHeight:12,fontWeight:'700',letterSpacing:1.5},badgeTitle:{marginTop:5,color:'#fff',fontSize:24,lineHeight:28,fontWeight:'700'},section:{width:'100%',maxWidth:760,alignSelf:'center',marginTop:58},sectionKicker:{paddingHorizontal:20,fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:1.6},sectionTitle:{paddingHorizontal:20,marginTop:8,fontSize:32,lineHeight:36,fontWeight:'700',letterSpacing:-1},sectionText:{paddingHorizontal:20,marginTop:10,fontSize:14,lineHeight:21},rail:{paddingHorizontal:20,paddingTop:22,paddingRight:32,gap:10},image:{height:300,borderRadius:30},visit:{width:'92%',maxWidth:728,alignSelf:'center',marginTop:58,borderRadius:36,padding:26,minHeight:310,justifyContent:'flex-end'},visitKicker:{color:'rgba(255,255,255,.54)',fontSize:10,lineHeight:13,fontWeight:'700',letterSpacing:1.6},visitTitle:{marginTop:9,color:'#fff',fontSize:32,lineHeight:36,fontWeight:'700',letterSpacing:-1},visitText:{marginTop:10,color:'rgba(255,255,255,.68)',fontSize:14,lineHeight:21},visitActions:{marginTop:24,gap:8},white:{height:50,borderRadius:25,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},whiteText:{color:'#111214',fontSize:13,lineHeight:17,fontWeight:'600'},dark:{height:50,borderRadius:25,borderWidth:1,borderColor:'rgba(255,255,255,.20)',alignItems:'center',justifyContent:'center'},darkText:{color:'#fff',fontSize:13,lineHeight:17,fontWeight:'600'}});
