import type { Language } from '@/src/lib/types';

export const homeCopy = {
  ru: {
    heroKicker: 'AUTO SALE UMAR · TASHKENT',
    heroTitle: 'Автомобиль,\nвыбранный точно.',
    heroText: 'Новые автомобили в наличии и в пути. Международный подбор, прозрачный статус и персональное сопровождение.',
    brandsKicker: 'ВЫБЕРИТЕ МАРКУ',
    brandsTitle: 'Начните с характера.',
    brandsText: 'Коллекция формируется из автомобилей, которые действительно есть в базе Auto Sale Umar.',
    showroomKicker: 'В ШОУРУМЕ',
    showroomTitle: 'Можно посмотреть сегодня.',
    showroomText: 'Автомобили, которые сейчас находятся в шоуруме и доступны для просмотра.',
    stockKicker: 'В НАЛИЧИИ',
    stockTitle: 'Без ожидания поставки.',
    stockText: 'Автомобили в шоуруме и на складе, которые можно купить без ожидания приезда.',
    transitKicker: 'В ПУТИ',
    transitTitle: 'Следующее поступление.',
    transitText: 'Следите за автомобилями, которые уже направляются в шоурум.',
    requestKicker: 'ПЕРСОНАЛЬНЫЙ ПОДБОР',
    requestTitle: 'Не нашли нужный автомобиль?',
    requestText: 'Укажите марку, модель, бюджет и срок покупки. Команда Auto Sale Umar начнёт поиск под ваш запрос.',
    requestAction: 'Найти автомобиль',
    compareKicker: 'СРАВНИТЕ ПЕРЕД ВЫБОРОМ',
    compareTitle: 'Два автомобиля. Один понятный выбор.',
    compareText: 'Сопоставьте цену, характеристики и комплектации реальных автомобилей Auto Sale Umar.',
    compareAction: 'Сравнить автомобили',
    showroomAboutKicker: 'О ШОУРУМЕ',
    showroomAboutTitle: 'Пространство для спокойного выбора.',
    showroomAboutText: 'Автомобиль остаётся в центре внимания, а атмосфера даёт время рассмотреть детали и принять решение без спешки.',
    bookKicker: 'МЕСТОПОЛОЖЕНИЕ',
    bookTitle: 'Забронировать визит',
    bookText: 'Выберите дату, время и автомобиль — команда шоурума увидит бронирование в Control System и подготовит визит.',
    exportKicker: 'МЕЖДУНАРОДНАЯ ПОСТАВКА',
    exportTitle: 'Ищем автомобиль там, где он есть.',
    exportText: 'Привозим новые автомобили под заказ из США, Канады, Кореи, ОАЭ, Европы, Великобритании и Австралии.',
    contactsKicker: 'КОНТАКТЫ',
    contactsTitle: 'Продолжим там, где удобно вам.',
    contactsText: 'Instagram остаётся главным каналом обзоров. Для консультации можно написать или позвонить напрямую.',
    trustKicker: '25 ЛЕТ В АВТОМОБИЛЬНОЙ СФЕРЕ',
    trustTitle: 'Доверие, которое выдерживает время.',
    trustText: 'Опыт Auto Sale Umar — это привычка отвечать за выбор, детали и результат.',
  },
  uz: {
    heroKicker: 'AUTO SALE UMAR · TOSHKENT',
    heroTitle: 'Aniq tanlangan\navtomobil.',
    heroText: 'Mavjud va yo‘ldagi yangi avtomobillar. Xalqaro tanlov, aniq status va shaxsiy kuzatuv.',
    brandsKicker: 'MARKANI TANLANG',
    brandsTitle: 'Xarakterdan boshlang.',
    brandsText: 'Kolleksiya Auto Sale Umar bazasida haqiqatan mavjud avtomobillardan tuziladi.',
    showroomKicker: 'SHOURUMDA',
    showroomTitle: 'Bugun ko‘rish mumkin.',
    showroomText: 'Hozir shourumda bo‘lgan va ko‘rish uchun mavjud avtomobillar.',
    stockKicker: 'MAVJUD',
    stockTitle: 'Yetkazib berishni kutmasdan.',
    stockText: 'Shourum va ombordagi, darhol sotib olish mumkin bo‘lgan avtomobillar.',
    transitKicker: 'YO‘LDA',
    transitTitle: 'Keyingi kelish.',
    transitText: 'Shourum tomon yo‘l olgan avtomobillar statusini kuzating.',
    requestKicker: 'SHAXSIY TANLOV',
    requestTitle: 'Kerakli avtomobilni topmadingizmi?',
    requestText: 'Marka, model, byudjet va muddatni ko‘rsating. Auto Sale Umar jamoasi qidiruvni boshlaydi.',
    requestAction: 'Avtomobil topish',
    compareKicker: 'TANLASHDAN OLDIN SOLISHTIRING',
    compareTitle: 'Ikki avtomobil. Bitta aniq tanlov.',
    compareText: 'Auto Sale Umar bazasidagi real avtomobillarning narxi va komplektatsiyasini solishtiring.',
    compareAction: 'Solishtirish',
    showroomAboutKicker: 'SHOURUM HAQIDA',
    showroomAboutTitle: 'Sokin tanlov uchun makon.',
    showroomAboutText: 'Avtomobil diqqat markazida qoladi, muhit esa detallarni ko‘rish va shoshmasdan qaror qilishga yordam beradi.',
    bookKicker: 'MANZIL',
    bookTitle: 'Tashrifni bron qilish',
    bookText: 'Sana, vaqt va avtomobilni tanlang — shourum jamoasi tashrifni tayyorlaydi.',
    exportKicker: 'XALQARO YETKAZIB BERISH',
    exportTitle: 'Avtomobil qayerda bo‘lsa, o‘sha yerdan topamiz.',
    exportText: 'AQSH, Kanada, Koreya, BAA, Yevropa, Buyuk Britaniya va Avstraliyadan buyurtma asosida avtomobil olib kelamiz.',
    contactsKicker: 'ALOQA',
    contactsTitle: 'Sizga qulay joyda davom etamiz.',
    contactsText: 'Instagram asosiy ko‘rib chiqish kanali. Maslahat uchun yozishingiz yoki qo‘ng‘iroq qilishingiz mumkin.',
    trustKicker: 'AVTOMOBIL SOHASIDA 25 YIL',
    trustTitle: 'Vaqt sinovidan o‘tgan ishonch.',
    trustText: 'Auto Sale Umar tajribasi — tanlov, detal va natija uchun javob berish odati.',
  },
} as const;

export const showroomStories = [
  ['Тишина снаружи. Характер внутри.', 'Пространство, где автомобиль говорит сам за себя.'],
  ['Комфорт начинается до поездки.', 'Спокойная клиентская зона и персональное внимание.'],
  ['Свет подчёркивает главное.', 'Архитектура раскрывает линии автомобиля, материалы и детали.'],
  ['Выбирайте своё.', 'Подберём модель, комплектацию и организуем путь автомобиля.'],
  ['Доверие строится на деталях.', 'Прозрачный статус и серьёзное сопровождение.'],
  ['Цифровая витрина. Живой шоурум.', 'Каталог и актуальные статусы работают как единая система.'],
] as const;

export const markets = ['🇺🇸 США', '🇨🇦 Канада', '🇰🇷 Корея', '🇦🇪 ОАЭ', '🇪🇺 Европа', '🇬🇧 Великобритания', '🇦🇺 Австралия'];

export function copyFor(language: Language) {
  return homeCopy[language];
}
